import Head from "next/head";
import Link from "next/link";
import Layout from "../../components/Layout/Layout";

export default function Terms() {
    return (
      <>
      <Head>
        <title>Terms | JoShare</title>
      </Head>

      <Layout>
        <div className="h-full w-full text-center">
          <div className="flex flex-col items-center"><h1 className="utility-header">Terms <span className="dot">.</span></h1></div>

          <div className="flex justify-center mb-6">

            <div className="columns-1 max-w-[1000px] lg:columns-2 gap-6 px-0 pr-5 lg:px-8">
              <div className="container">
                <h1>Privacy Policy</h1>
                <p>Last updated: January 1, 2023</p>
                <br />
                <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                <br />
                <p>We use some of Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                
              </div>

              <div className="container">
                <h1>Interpretation and Definitions</h1>

                <h2>Interpretation</h2>
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                <br />

                <p>Definitions</p>

                <br />
                <p>For the purposes of this Privacy Policy:</p>
                <br />


                <ul className="list-disc pl-5">
                  <li>
                    <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to joShare | File Sharing.</p>
                  </li>
                  <li>
                    <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                  </li>
                  <li>
                    <p><strong>Country</strong> refers to:  Bangladesh</p>
                  </li>
                  <li>
                    <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                  </li>
                  <li>
                    <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. Although besides your email we do not use your personal data and that&apos;s also optional. You have to provide your mail if you want to send any e-mail using our service.</p>
                  </li>
                  <li>
                    <p><strong>Service</strong> refers to the Website.</p>
                  </li>
                  <li>
                    <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                  </li>
                  <li>
                    <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                  </li>
                  <li>
                    <p><strong>Website</strong> refers to joShare | File Sharing, accessible from <a href="https://joshare.xyz" target="_blank" rel="noreferrer">https://joshare.xyz</a></p>
                  </li>
                  <li>
                    <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                  </li>
                </ul>
                
              </div>

              <div className="container">
                <h1>Children's Privacy</h1>
                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                <br />
                <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
                <br />
              </div>

              <div className="container">
                <h1>Links to Other Websites</h1>
                <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                <br />
                <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                <br />
              </div>

              <div className="container">
                <h1>Changes to this Privacy Policy</h1>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                <br />
                <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
                <br />
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

              </div>

              <div className="container">
                <p>Disclosure of Your Personal Data</p>
                <br />

                <h2>Law enforcement</h2>
                <br />
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                <br />  
                <h2>Other legal requirements</h2>
                <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <br />


                <ul className="list-disc pl-8">
                  <li>Comply with a legal obligation</li>
                  <li>Protect and defend the rights or property of the Company</li>
                  <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                  <li>Protect the personal safety of Users of the Service or the public</li>
                  <li>Protect against legal liability</li>
                </ul>
                <br />

                <h2>Security of Your Personal Data</h2>
                <br />
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

              </div>

              <div className="container">
                <h1>Collecting and Using Your Personal Data</h1>
                <h2>Types of Data Collected</h2>
                <br />
                <h2>Personal Data</h2>
                <br />
                <p>Generally we do not collect any personal data besides E-mail address and that's also optional. You have to provide your mail if you want to send any e-mail using our service. Even your email information gets deleted after your PIN expires.</p>
                <br />

                <ul className="list-disc pl-8">
                  <li>
                    <p>Email address</p>
                  </li>
                  <li>
                    <p>Usage Data</p>
                  </li>
                </ul>

                <br />
                <h2>Usage Data</h2>
                <br />
                <p>Usage Data is collected automatically when using the Service.</p>
                <br />
                <p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <br />
                
                <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                <br />


                <h2>Tracking Technologies and Cookies</h2>

                <br />
                <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                <br />

                <ul className="list-disc pl-8">
                  <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                </ul>
                <br />

                <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
                <br />
                <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                <br />
                <ul className="list-disc pl-8">
                  <li>
                    <p ><strong>Necessary / Essential Cookies</strong></p>
                    <p >Type: Session Cookies</p>
                    <p>Administered by: Us</p>
                    <p >Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                  </li>
                  <li>
                    <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                  </li>
                  <li>
                  <p><strong>Functionality Cookies</strong></p>
                  <p>Type: Persistent Cookies</p>
                  <p>Administered by: Us</p>
                  <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                  </li>
                </ul>
                <br />

                <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                <br />
                <h2>Use of Your Personal Data</h2>
                <br />
                <p>We may share Your personal information in the following situations:</p>
                <br />

                <ul className="list-disc pl-8">
                  <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>
                  <li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
                </ul>

                <br />

                <h2>Retention of Your Personal Data</h2>
                <br />
                <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <br />

                <h2>Transfer of Your Personal Data</h2>
                <br />
                <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                <br />
                <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                <br />
                <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                <br />

                
              </div>


            </div>
          </div>
          
          <div className="flex flex-col items-center mb-2"> 
              <h1 className="utility-header">Contact</h1>

              <Link className="cursor-pointer hover:scale-110 transition-all duration-300 text-indigo-800 dark:text-indigo-400" href="mailto:support@joshare.xyz">support@joshare.xyz</Link>

            </div>

        </div>
      </Layout>
      </>
      )
}