import Head from 'next/head'
import CreatePinButton from '../components/Button/CreatePinButton'
import HomeInput from '../components/InputBox/HomeInput'
import Logo from '../components/Logo/Logo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="max-w-screen overflow-hidden flex flex-col justify-center items-center">
          <div className="w-full mt-28 lg:mt-44">
            <div className="max-w-[400px] lg:max-w-[600px] mx-auto">
            <Logo />
            </div>

          </div>   

          <div className="flex-col my-3 mb-16">
            <HomeInput />
            <CreatePinButton />
          </div>

        </div>
      </div>
    </>
  )
}
